import Fastify from "fastify";
import fastifyJwt from "@fastify/jwt";
import fastifyCookie from "@fastify/cookie";
import fastifyCors from "@fastify/cors";
import fastifyWebsocket from "@fastify/websocket";
import fastifyRateLimit from "@fastify/rate-limit";
import fs from "fs";
import path from "path";
import { config } from "./config";
import { authRoutes } from "./routes/auth";
import { enrollmentRoutes } from "./routes/enrollment";
import { metricsRoutes } from "./routes/metrics";
import { workstationRoutes } from "./routes/workstations";
import { alertRoutes } from "./routes/alerts";
import { discoveryRoutes } from "./routes/discovery";
import { deployRoutes } from "./routes/deploy";
import { agentWsRoutes } from "./ws/agentHandler";
import { browserWsRoutes } from "./ws/browserHandler";
import { raiseHeartbeatAlert } from "./services/alertEngine";
import { query } from "./db";

const app = Fastify({ logger: { level: "info" } });

async function main() {
  // Plugins
  await app.register(fastifyCors, {
    origin: config.cors.origin,
    credentials: true,
  });

  await app.register(fastifyRateLimit, {
    max: parseInt(process.env.RATE_LIMIT_MAX ?? "600"),
    timeWindow: "1 minute",
  });

  await app.register(fastifyCookie);

  await app.register(fastifyJwt, {
    secret: config.jwt.secret,
    cookie: { cookieName: "wms_token", signed: false },
  });

  await app.register(fastifyWebsocket);

  // Routes (each route file declares full /api/... paths)
  await app.register(authRoutes);
  await app.register(enrollmentRoutes);
  await app.register(metricsRoutes);
  await app.register(workstationRoutes);
  await app.register(alertRoutes);
  await app.register(discoveryRoutes);
  await app.register(deployRoutes);

  // WebSocket routes
  await app.register(agentWsRoutes);
  await app.register(browserWsRoutes);

  // Health check
  app.get("/health", async () => ({ ok: true }));

  // ── Pre-built binary downloads ────────────────────────────────────────────
  const BINARIES_DIR = path.join(__dirname, "..", "binaries");

  app.get<{ Params: { file: string } }>("/download/:file", async (req, reply) => {
    const file = req.params.file.replace(/[^a-z0-9.\-_]/gi, "");
    const filePath = path.join(BINARIES_DIR, file);
    if (!fs.existsSync(filePath)) {
      return reply.code(404).send({ error: "Binary not found. Run: npm run build:agent" });
    }
    reply.header("Content-Disposition", `attachment; filename="${file}"`);
    reply.type("application/octet-stream");
    return reply.send(fs.createReadStream(filePath));
  });

  // ── /q/:token — zero-credential install (token embedded in URL) ───────────
  // macOS: curl -fsSL http://server:4000/q/TOKEN | sudo bash
  // Linux: curl -fsSL http://server:4000/q/TOKEN | sudo bash
  app.get<{ Params: { token: string } }>("/q/:token", async (req, reply) => {
    const token = req.params.token.replace(/[^a-f0-9]/gi, "");
    const host  = req.headers["host"] ?? `localhost:${config.port}`;
    const serverBase = `${req.protocol}://${host}`;
    const wsUrl = serverBase.replace(/^http/, "ws") + "/ws/agent";

    reply.type("text/plain");
    return `#!/usr/bin/env bash
# WMS Agent — zero-credential installer
# Generated by WorkstationMonSys. Run with: curl -fsSL ${serverBase}/q/${token} | sudo bash
set -euo pipefail

WMS_TOKEN="${token}"
WMS_SERVER="${serverBase}"
WMS_WS="${wsUrl}"
INSTALL_DIR="/usr/local/bin"
STATE_DIR="/etc/wms-agent"
BINARY="wms-agent"

echo "==> WorkstationMonSys Agent Installer"
echo "    Server : $WMS_SERVER"

OS="\$(uname -s | tr '[:upper:]' '[:lower:]')"
ARCH="\$(uname -m)"
case "\$ARCH" in
  x86_64)  ARCH="amd64" ;;
  arm64|aarch64) ARCH="arm64" ;;
  *) echo "Unsupported arch: \$ARCH"; exit 1 ;;
esac

echo "    Platform: \$OS-\$ARCH"

# ── Download pre-built binary ─────────────────────────────────────────────
DOWNLOAD_URL="\$WMS_SERVER/download/wms-agent-\$OS-\$ARCH"
echo "==> Downloading agent binary..."
if command -v curl &>/dev/null; then
  curl -fsSL "\$DOWNLOAD_URL" -o "/tmp/\$BINARY"
elif command -v wget &>/dev/null; then
  wget -qO "/tmp/\$BINARY" "\$DOWNLOAD_URL"
else
  echo "ERROR: curl or wget required"; exit 1
fi
chmod +x "/tmp/\$BINARY"

sudo mkdir -p "\$STATE_DIR" "\$INSTALL_DIR"
sudo mv "/tmp/\$BINARY" "\$INSTALL_DIR/\$BINARY"
echo "    Installed: \$INSTALL_DIR/\$BINARY"

# ── Install as system service ─────────────────────────────────────────────
if [ "\$OS" = "darwin" ]; then
  PLIST_DIR="/Library/LaunchDaemons"
  PLIST_LABEL="com.wms.agent"
  sudo tee "\$PLIST_DIR/\$PLIST_LABEL.plist" > /dev/null <<PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0"><dict>
  <key>Label</key>             <string>\$PLIST_LABEL</string>
  <key>ProgramArguments</key>  <array><string>\$INSTALL_DIR/\$BINARY</string></array>
  <key>EnvironmentVariables</key><dict>
    <key>WMS_SERVER_URL</key>  <string>\$WMS_WS</string>
    <key>WMS_ENROLL_TOKEN</key><string>\$WMS_TOKEN</string>
    <key>WMS_STATE_FILE</key>  <string>\$STATE_DIR/state.json</string>
    <key>WMS_INTERVAL</key>    <string>10s</string>
  </dict>
  <key>RunAtLoad</key><true/><key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>/var/log/wms-agent.log</string>
  <key>StandardErrorPath</key><string>/var/log/wms-agent.log</string>
</dict></plist>
PLIST
  sudo launchctl unload "\$PLIST_DIR/\$PLIST_LABEL.plist" 2>/dev/null || true
  sudo launchctl load   "\$PLIST_DIR/\$PLIST_LABEL.plist"
  echo "==> Agent installed as launchd service."
  echo "    Logs: sudo tail -f /var/log/wms-agent.log"

else
  # Linux — systemd
  sudo tee /etc/systemd/system/wms-agent.service > /dev/null <<SERVICE
[Unit]
Description=WMS Monitoring Agent
After=network.target

[Service]
ExecStart=\$INSTALL_DIR/\$BINARY
Environment=WMS_SERVER_URL=\$WMS_WS
Environment=WMS_ENROLL_TOKEN=\$WMS_TOKEN
Environment=WMS_STATE_FILE=\$STATE_DIR/state.json
Environment=WMS_INTERVAL=10s
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
SERVICE
  sudo systemctl daemon-reload
  sudo systemctl enable --now wms-agent
  echo "==> Agent installed as systemd service."
  echo "    Logs: journalctl -u wms-agent -f"
fi
`;
  });

  // Windows PowerShell variant
  app.get<{ Params: { token: string } }>("/q/:token/windows", async (req, reply) => {
    const token = req.params.token.replace(/[^a-f0-9]/gi, "");
    const host  = req.headers["host"] ?? `localhost:${config.port}`;
    const serverBase = `${req.protocol}://${host}`;
    const wsUrl = serverBase.replace(/^http/, "ws") + "/ws/agent";
    reply.type("text/plain");
    const ps = [
      `# WMS Agent installer — Windows PowerShell`,
      `$ErrorActionPreference = "Stop"`,
      `$Token  = "${token}"`,
      `$Server = "${serverBase}"`,
      `$WsUrl  = "${wsUrl}"`,
      `$Dir    = "C:\\wms-agent"`,
      `$Binary = "wms-agent.exe"`,
      ``,
      `Write-Host "==> WorkstationMonSys Agent Installer"`,
      `New-Item -ItemType Directory -Force $Dir | Out-Null`,
      `Write-Host "==> Downloading agent binary..."`,
      `Invoke-WebRequest -Uri "$Server/download/wms-agent-windows-amd64.exe" -OutFile "$Dir\\$Binary" -UseBasicParsing`,
      `$action   = New-ScheduledTaskAction -Execute "$Dir\\$Binary"`,
      `$trigger  = New-ScheduledTaskTrigger -AtStartup`,
      `$settings = New-ScheduledTaskSettingsSet -RestartInterval (New-TimeSpan -Seconds 10) -RestartCount 999`,
      `$principal = New-ScheduledTaskPrincipal -UserId "SYSTEM" -LogonType ServiceAccount -RunLevel Highest`,
      `$task = New-ScheduledTask -Action $action -Trigger $trigger -Settings $settings -Principal $principal`,
      `Register-ScheduledTask -TaskName "WMSAgent" -InputObject $task -Force | Out-Null`,
      `[System.Environment]::SetEnvironmentVariable("WMS_SERVER_URL",   $WsUrl, "Machine")`,
      `[System.Environment]::SetEnvironmentVariable("WMS_ENROLL_TOKEN", $Token, "Machine")`,
      `[System.Environment]::SetEnvironmentVariable("WMS_STATE_FILE",   "$Dir\\state.json", "Machine")`,
      `[System.Environment]::SetEnvironmentVariable("WMS_INTERVAL",     "10s", "Machine")`,
      `Start-ScheduledTask -TaskName "WMSAgent"`,
      `Write-Host "==> Agent installed and running."`,
    ].join("\r\n");
    return ps;
  });

  // Start heartbeat watchdog
  startHeartbeatWatchdog();

  await app.listen({ port: config.port, host: "0.0.0.0" });
  app.log.info(`Server listening on port ${config.port}`);
}

// Detect agents that haven't sent a metric in >5 minutes
function startHeartbeatWatchdog() {
  setInterval(async () => {
    try {
      const stale = await query<{ id: string }>(
        `SELECT id FROM workstations
         WHERE status != 'offline'
           AND last_seen_at < NOW() - INTERVAL '5 minutes'`
      );
      for (const ws of stale) {
        await raiseHeartbeatAlert(ws.id);
      }
    } catch (err) {
      app.log.error({ err }, "Heartbeat watchdog error");
    }
  }, config.alerts.intervalMs);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
